trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/*.html'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy HTML files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'pinballgame'
  displayName: 'Publish Artifact'